version: '2'
services:
  moodle:
    container_name: moodle
    image: docker.io/bitnami/moodle:latest
    restart: always
    ports:
      - 80:8080
      - 443:8443
    environment:
IP BASE DA DATOS 
      - MOODLE_DATABASE_HOST=172.31.93.242
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
